# services:
#   db:
#     image: postgres:16
#     container_name: db
#     restart: always
#     environment:
#       POSTGRES_DB: ${DB_NAME:-postgres}
#       POSTGRES_USER: ${DB_USER:-iassine}
#       POSTGRES_PASSWORD: ${DB_PASSWORD:-iassine123}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   web:
#     build: .
#     container_name: web
#     command: >
#       sh -c "
#       python manage.py migrate &&
#       gunicorn meu_projecto.wsgi:application
#       --bind 0.0.0.0:8000
#       --workers 1
#       --timeout 180
#       "
#     volumes:
#       - .:/meu_projecto
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       db:
#         condition: service_healthy

# volumes:
#   postgres_data:



services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-iassine}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-iassine123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: web
    command: gunicorn meu_projecto.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/meu_projecto
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:



# # services:
# #   web:
# #     build: .
# #     command: python manage.py runserver 0.0.0.0:8000
# #     volumes:
# #       - .:/meu_projecto
# #     ports:
# #       - "8000:8000"
# #     depends_on:
# #       - db

# #   db:
# #     image: postgres:16
# #     environment:
# #       POSTGRES_DB: postgres
# #       POSTGRES_USER: iassine
# #       POSTGRES_PASSWORD: iassine123
# #     volumes:
# #       - postgres_data:/var/lib/postgresql/data

# # volumes:
# #   postgres_data:
