services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
      # sh -c "
      # until pg_isready -h db -p 5432 -U iassine; do
      #   echo 'Aguardando PostgreSQL...';
      #   sleep 2;
      # done &&
      # python manage.py migrate &&
      # python manage.py runserver 0.0.0.0:8000
      # "
    volumes:
      - .:/meu_projecto
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: iassine
      POSTGRES_PASSWORD: iassine123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
